In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("hr_dataset.csv")
print(data)

      Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales
1      49        No  Travel_Frequently        279  Research & Development
2      37       Yes      Travel_Rarely       1373  Research & Development
3      33        No  Travel_Frequently       1392  Research & Development
4      27        No      Travel_Rarely        591  Research & Development
...   ...       ...                ...        ...                     ...
1465   36        No  Travel_Frequently        884  Research & Development
1466   39        No      Travel_Rarely        613  Research & Development
1467   27        No      Travel_Rarely        155  Research & Development
1468   49        No  Travel_Frequently       1023                   Sales
1469   34        No      Travel_Rarely        628  Research & Development

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1
1                    8          1  Life Sciences              1
2                    2          2          Other              1
3                    3          4  Life Sciences              1
4                    2          1        Medical              1
...                ...        ...            ...            ...
1465                23          2        Medical              1
1466                 6          1        Medical              1
1467                 4          3  Life Sciences              1
1468                 2          3        Medical              1
1469                 8          3        Medical              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80
1                  2  ...                         4            80
2                  4  ...                         2            80
3                  5  ...                         3            80
4                  7  ...                         4            80
...              ...  ...                       ...           ...
1465            2061  ...                         3            80
1466            2062  ...                         1            80
1467            2064  ...                         2            80
1468            2065  ...                         4            80
1469            2068  ...                         1            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0
1                    1                 10                      3
2                    0                  7                      3
3                    0                  8                      3
4                    1                  6                      3
...                ...                ...                    ...
1465                 1                 17                      3
1466                 1                  9                      5
1467                 1                  6                      0
1468                 0                 17                      3
1469                 0                  6                      3

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4
1                  3              10                  7
2                  3               0                  0
3                  3               8                  7
4                  3               2                  2
...              ...             ...                ...
1465               3               5                  2
1466               3               7                  7
1467               3               6                  2
1468               2               9                  6
1469               4               4                  3

      YearsSinceLastPromotion  YearsWithCurrManager
0                           0                     5
1                           1                     7
2                           0                     0
3                           3                     0
4                           2                     2
...                       ...                   ...
1465                        0                     3
1466                        1                     7
1467                        0                     3
1468                        0                     8
1469                        1                     2

[1470 rows x 35 columns]

In [3]:
data.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [5]:
data=data.drop_duplicates()

In [7]:
data.columns=data.columns.str.strip().str.lower()

In [9]:
data.dropna(inplace=True)

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1470 non-null   int64
 1   attrition                 1470 non-null   str
 2   businesstravel            1470 non-null   str
 3   dailyrate                 1470 non-null   int64
 4   department                1470 non-null   str
 5   distancefromhome          1470 non-null   int64
 6   education                 1470 non-null   int64
 7   educationfield            1470 non-null   str
 8   employeecount             1470 non-null   int64
 9   employeenumber            1470 non-null   int64
 10  environmentsatisfaction   1470 non-null   int64
 11  gender                    1470 non-null   str
 12  hourlyrate                1470 non-null   int64
 13  jobinvolvement            1470 non-null   int64
 14  joblevel                  1470 non-null   int64
 15  jobrole                   1470 non-null   str
 16  jobsatisfaction           1470 non-null   int64
 17  maritalstatus             1470 non-null   str
 18  monthlyincome             1470 non-null   int64
 19  monthlyrate               1470 non-null   int64
 20  numcompaniesworked        1470 non-null   int64
 21  over18                    1470 non-null   str
 22  overtime                  1470 non-null   str
 23  percentsalaryhike         1470 non-null   int64
 24  performancerating         1470 non-null   int64
 25  relationshipsatisfaction  1470 non-null   int64
 26  standardhours             1470 non-null   int64
 27  stockoptionlevel          1470 non-null   int64
 28  totalworkingyears         1470 non-null   int64
 29  trainingtimeslastyear     1470 non-null   int64
 30  worklifebalance           1470 non-null   int64
 31  yearsatcompany            1470 non-null   int64
 32  yearsincurrentrole        1470 non-null   int64
 33  yearssincelastpromotion   1470 non-null   int64
 34  yearswithcurrmanager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 510.8 KB

In [12]:
data.columns=data.columns.str.strip().str.lower().str.replace(' ', '_')
print(data.columns)

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager'],
      dtype='str')

In [ ]:
data.describe()

,age,dailyrate,distancefromhome,education,employeecount,employeenumber,environmentsatisfaction,hourlyrate,jobinvolvement,joblevel,...,relationshipsatisfaction,standardhours,stockoptionlevel,totalworkingyears,trainingtimeslastyear,worklifebalance,yearsatcompany,yearsincurrentrole,yearssincelastpromotion,yearswithcurrmanager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [16]:
data.nunique()

age                           43
attrition                      2
businesstravel                 3
dailyrate                    886
department                     3
distancefromhome              29
education                      5
educationfield                 6
employeecount                  1
employeenumber              1470
environmentsatisfaction        4
gender                         2
hourlyrate                    71
jobinvolvement                 4
joblevel                       5
jobrole                        9
jobsatisfaction                4
maritalstatus                  3
monthlyincome               1349
monthlyrate                 1427
numcompaniesworked            10
over18                         1
overtime                       2
percentsalaryhike             15
performancerating              2
relationshipsatisfaction       4
standardhours                  1
stockoptionlevel               4
totalworkingyears             40
trainingtimeslastyear          7
worklifebalance                4
yearsatcompany                37
yearsincurrentrole            19
yearssincelastpromotion       16
yearswithcurrmanager          18
dtype: int64

In [24]:


bins = [18, 25, 35, 45, 55, 65]

labels = [
    '18-25',
    '26-35',
    '36-45',
    '46-55',
    '56-65'
]

data['age_group'] = pd.cut(data['age'], bins=bins, labels=labels)

print(data['age_group'].head())

0    36-45
1    46-55
2    36-45
3    26-35
4    26-35
Name: age_group, dtype: category
Categories (5, str): ['18-25' < '26-35' < '36-45' < '46-55' < '56-65']

In [23]:
data['age_group'].value_counts().sort_index()

age_group
18-25    115
26-35    606
36-45    468
46-55    226
56-65     47
Name: count, dtype: int64

In [26]:
education_map = {
    1: 'Below College',
    2: 'College',
    3: 'Bachelor',
    4: 'Master',
    5: 'Doctor'
}

data['education_level'] = data['education'].map(education_map)
print(data[['education', 'education_level']].head())

   education education_level
0          2         College
1          1   Below College
2          2         College
3          4          Master
4          1   Below College

In [30]:
jobsatistfaction_level ={
    1: 'Low',
    2: 'Medium',
    3: 'High',
    4: 'Very High'
}
data['jobsatisfaction_level'] = data['jobsatisfaction'].map(satistfaction_level)

In [31]:
environment_satisfaction_level = {
    1: 'Low',
    2: 'Medium',
    3: 'High',
    4: 'Very High'
}
data['environment_satisfaction_level'] = data['environmentsatisfaction'].map(environment_satisfaction_level)

In [32]:
worklife_balance_level = {
    1: 'Bad',
    2: 'Good',
    3: 'Better',
    4: 'Best'
}
data['worklife_balance_level']=data['worklifebalance'].map(worklife_balance_level)

In [33]:
jobinvalment_level = {
    1: 'Low',
    2: 'Medium',
    3: 'High',
    4: 'Very High'
}
data['jobinvalment_level'] = data['jobinvolvement'].map(jobinvalment_level)

In [36]:
performance_level = {
    1: 'Low',
    2: 'Good',
    3: 'Excellent',
    4: 'Outstanding'
}
data['performance_level'] = data['performancerating'].map(performance_level)

In [37]:
print(data.head())

   age attrition     businesstravel  dailyrate              department  \
0   41       Yes      Travel_Rarely       1102                   Sales
1   49        No  Travel_Frequently        279  Research & Development
2   37       Yes      Travel_Rarely       1373  Research & Development
3   33        No  Travel_Frequently       1392  Research & Development
4   27        No      Travel_Rarely        591  Research & Development

   distancefromhome  education educationfield  employeecount  employeenumber  \
0                 1          2  Life Sciences              1               1
1                 8          1  Life Sciences              1               2
2                 2          2          Other              1               4
3                 3          4  Life Sciences              1               5
4                 2          1        Medical              1               7

   ...  yearssincelastpromotion yearswithcurrmanager  age_group  \
0  ...                        0                    5      36-45
1  ...                        1                    7      46-55
2  ...                        0                    0      36-45
3  ...                        3                    0      26-35
4  ...                        2                    2      26-35

   education_level  satisfaction_level jobsatisfaction_level  \
0          College           Very High             Very High
1    Below College              Medium                Medium
2          College                High                  High
3           Master                High                  High
4    Below College              Medium                Medium

   environment_satisfaction_level worklife_balance_level  jobinvalment_level  \
0                          Medium                    Bad                High
1                            High                 Better              Medium
2                       Very High                 Better              Medium
3                       Very High                 Better                High
4                             Low                 Better                High

   performance_level
0          Excellent
1        Outstanding
2          Excellent
3          Excellent
4          Excellent

[5 rows x 43 columns]

In [39]:
data.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'age_group', 'education_level',
       'satisfaction_level', 'jobsatisfaction_level',
       'environment_satisfaction_level', 'worklife_balance_level',
       'jobinvalment_level', 'performance_level'],
      dtype='str')

In [40]:
relationships_satisfaction_level = {
    1: 'Low',
    2: 'Medium',
    3: 'High',
    4: 'Very High'
}
data['relationships_satisfaction_level'] = data['relationshipsatisfaction'].map(relationships_satisfaction_level)

In [41]:
data['attrition_flag'] = data['attrition'].map({'Yes':1,'No':0})

In [ ]:
# Employee Attrition rate

attrition_rate = (
    data['attrition'].value_counts(normalize=True) * 100
)

print(attrition_rate)

attrition
No     83.877551
Yes    16.122449
Name: proportion, dtype: float64

In [45]:
dept_attrition = pd.crosstab(
    data['department'],
    data['attrition']
)
print(dept_attrition)

attrition                No  Yes
department
Human Resources          51   12
Research & Development  828  133
Sales                   354   92

In [46]:
data.groupby('department')['monthlyincome'].mean()

department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: monthlyincome, dtype: float64

In [47]:
pd.crosstab(
    data['overtime'],
    data['attrition'],
    normalize='index'
) * 100

attrition         No        Yes
overtime
No         89.563567  10.436433
Yes        69.471154  30.528846

In [48]:
data['attrition'].value_counts()

attrition
No     1233
Yes     237
Name: count, dtype: int64

In [49]:
(data['attrition'].value_counts(normalize=True) * 100).round(2)

attrition
No     83.88
Yes    16.12
Name: proportion, dtype: float64

In [53]:
#Gender Analysis
gender_attrition = pd.crosstab(
    data['gender'],
    data['attrition']
)
print(gender_attrition)

attrition   No  Yes
gender
Female     501   87
Male       732  150

In [52]:
pd.crosstab(
    data['age_group'],
    data['attrition']
)

attrition   No  Yes
age_group
18-25       75   40
26-35      490  116
36-45      425   43
46-55      200   26
56-65       39    8

In [57]:
# Work-Life Balance Analysis
pd.crosstab(
    data['worklife_balance_level'],
    data['attrition'],
    normalize='index'
) * 100

attrition                      No        Yes
worklife_balance_level
Bad                     68.750000  31.250000
Best                    82.352941  17.647059
Better                  85.778275  14.221725
Good                    83.139535  16.860465

In [55]:
#Stock Option Analysis
pd.crosstab(
    data['stockoptionlevel'],
    data['attrition'],
    normalize='index'
) * 100

attrition                No        Yes
stockoptionlevel
0                 75.594295  24.405705
1                 90.604027   9.395973
2                 92.405063   7.594937
3                 82.352941  17.647059

In [58]:
data.groupby('attrition')['yearsatcompany'].mean()

attrition
No     7.369019
Yes    5.130802
Name: yearsatcompany, dtype: float64

In [59]:
pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (2.0.49)
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: greenlet>=1 in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [60]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (2.0.49)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (9.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
import mysql.connector

In [67]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="divya",
    database="hr_analytics"
)

ProgrammingError: 1049 (42000): Unknown database 'hr_analytics'

In [68]:
pip install psycopg2-binary sqlachemy

Requirement already satisfied: psycopg2-binary in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement sqlachemy (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for sqlachemy

In [69]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kk\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [70]:
import sqlalchemy
import psycopg2

print("Packages installed successfully!")

Packages installed successfully!

In [71]:
from sqlalchemy import create_engine

In [72]:
engine = create_engine(
    "postgresql://postgres:divya@localhost:5432/hr_analytics"
)

In [73]:
data.to_sql(
    name='hr_dataset',
    con=engine,
    if_exists='replace',
    index=False
)

print("Dataset uploaded successfully!")

Dataset uploaded successfully!

In [74]:
data.to_excel('hr_dataset.xlsx', index=False)